name: pyspark-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - openjdk=11
  - pyspark=3.5.0
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - graphviz
  - pydotplus
  - seaborn
  - scipy
  - mlxtend
  - mlflow
